// Includes for MQL code compatibility.
#include "exceptions.h"
#include "const.h"
#include "math.h"
#include "datatype.h"
#include "string.h"
#include "time.h"
#include "predefined.h"
#include "convert.h"
#include "array.h"
#include "enum.h"
#include "common.h"
#include "file.h"
#include "terminal.h"
#include "account.h"
#include "symbolinfo.h"
#include "indicator.h"
#include "trading.h"
