//+------------------------------------------------------------------+
//|                                                   FX31337 engine |
//|                                 Copyright 2016-2021, EA31337 Ltd |
//|                                       https://github.com/FX31337 |
//+------------------------------------------------------------------+

/**
 * @file
 * Main file.
 */

#include <stdio.h>

using namespace std;

// Includes for MQL code compatibility.
#include "includes/mql/all.h"

// Class includes.
//#include "account.h"
//#include "terminal.h"

//#include "classes/Account.mqh"
//#include "classes/Account.define.h"
//#include "classes/Account.enum.h"
//#include "classes/Account.struct.h"
//#include "classes/Action.mqh"
//#include "classes/Action.enum.h"
//#include "classes/Action.struct.h"
//#include "classes/Array.mqh"
//#include "classes/Bar.enum.h"
//#include "classes/Bar.struct.h"
//#include "classes/BasicTrade.mqh"
//#include "classes/Buffer.mqh"
//#include "classes/BufferStruct.mqh"
//#include "classes/Chart.mqh"
//#include "classes/Chart.define.h"
//#include "classes/Chart.enum.h"
//#include "classes/Chart.struct.h"
//#include "classes/Chart.struct.serialize.h"
//#include "classes/Chart.struct.tf.h"
//#include "classes/Collection.mqh"
//#include "classes/Condition.mqh"
//#include "classes/Condition.enum.h"
//#include "classes/Condition.struct.h"
//#include "classes/Config.mqh"
//#include "classes/Convert.mqh"
//#include "classes/Data.define.h"
//#include "classes/Data.enum.h"
//#include "classes/Data.struct.h"
//#include "classes/Database.mqh"
//#include "classes/DateTime.mqh"
//#include "classes/DateTime.enum.h"
//#include "classes/DateTime.struct.h"
//#include "classes/Dict.mqh"
//#include "classes/DictBase.mqh"
//#include "classes/DictIteratorBase.mqh"
//#include "classes/DictObject.mqh"
//#include "classes/DictSlot.mqh"
//#include "classes/DictStruct.mqh"
//#include "classes/Draw.mqh"
//#include "classes/DrawIndicator.mqh"
//#include "classes/EA.mqh"
//#include "classes/EA.enum.h"
//#include "classes/EA.struct.h"
//#include "classes/File.mqh"
//#include "classes/Indicator.mqh"
//#include "classes/Indicator.define.h"
//#include "classes/Indicator.enum.h"
//#include "classes/Indicator.struct.h"
//#include "classes/Indicator.struct.serialize.h"
//#include "classes/IndicatorData.mqh"
//#include "classes/Inet.mqh"
//#include "classes/Log.mqh"
//#include "classes/Mail.mqh"
//#include "classes/Market.mqh"
//#include "classes/Market.struct.h"
//#include "classes/Math.h"
//#include "classes/Math.enum.h"
//#include "classes/Math.struct.h"
//#include "classes/Matrix.mqh"
//#include "classes/MD5.mqh"
//#include "classes/MQL4.mqh"
#include "classes/MQL5.mqh"
//#include "classes/Msg.mqh"
//#include "classes/Object.mqh"
//#include "classes/Order.mqh"
//#include "classes/Order.define.h"
//#include "classes/Order.enum.h"
//#include "classes/Order.struct.h"
//#include "classes/Orders.mqh"
//#include "classes/Pattern.mqh"
//#include "classes/Pattern.enum.h"
//#include "classes/Pattern.struct.h"
//#include "classes/Profiler.mqh"
//#include "classes/Redis.mqh"
//#include "classes/Redis.struct.h"
//#include "classes/Refs.mqh"
//#include "classes/Refs.struct.h"
//#include "classes/Registry.mqh"
//#include "classes/RegistryBinary.mqh"
//#include "classes/Report.mqh"
//#include "classes/Serializer.mqh"
//#include "classes/Serializer.define.h"
//#include "classes/Serializer.enum.h"
//#include "classes/SerializerBinary.mqh"
//#include "classes/SerializerConverter.mqh"
//#include "classes/SerializerCsv.mqh"
//#include "classes/SerializerDict.mqh"
//#include "classes/SerializerJson.mqh"
//#include "classes/SerializerNode.mqh"
//#include "classes/SerializerNode.enum.h"
//#include "classes/SerializerNodeIterator.mqh"
//#include "classes/SerializerNodeParam.mqh"
//#include "classes/SerializerObject.mqh"
//#include "classes/Session.mqh"
//#include "classes/SetFile.mqh"
//#include "classes/Socket.mqh"
//#include "classes/Stats.mqh"
//#include "classes/Strategy.mqh"
//#include "classes/Strategy.enum.h"
//#include "classes/Strategy.struct.h"
//#include "classes/String.mqh"
//#include "classes/SummaryReport.mqh"
//#include "classes/SVG.mqh"
//#include "classes/SymbolInfo.mqh"
//#include "classes/SymbolInfo.define.h"
//#include "classes/SymbolInfo.enum.h"
//#include "classes/SymbolInfo.struct.h"
//#include "classes/Task.mqh"
//#include "classes/Task.enum.h"
//#include "classes/Task.struct.h"
#include "classes/Terminal.mqh"
//#include "classes/Terminal.define.h"
//#include "classes/Terminal.enum.h"
//#include "classes/Terminal.struct.h"
//#include "classes/Test.mqh"
//#include "classes/Tester.mqh"
//#include "classes/Tests.mqh"
//#include "classes/Ticker.mqh"
//#include "classes/Timer.mqh"
//#include "classes/Trade.mqh"
//#include "classes/Trade.enum.h"
//#include "classes/Trade.struct.h"
//#include "classes/Web.mqh"

void main() {
  Terminal *terminal = new Terminal();
  delete terminal;
}
